### ISSUE TITLE
リモートプレイヤーのマッチングシステムの検討

### ISSUE THREAD

**Issue by tkuramot** [kaaaaakun/ft_transcendence#101]
どのプレイヤーとどのプレイヤーが対戦するのか、その順番をどういうふうに管理するのか、技術的な面も含めてて、決める。

miroに記述したのでレビューお願いします。
https://miro.com/app/board/uXjVKDAW9_g=/?moveToWidget=3458764605448363785&cot=14
シンプル対戦およびトーナメント対戦のマッチング方法と、技術的な要素の概要を検討しました。

@tkuramot @soma0822 @soragogo @kaaaaakun 
Estimate result: 5

**Comment by soma0822** [comment]
@jizots miroにコメントを追加しました

**Comment by jizots** [comment]
再レビューお願いします。
@tkuramot @soma0822 @soragogo @kaaaaakun 

トーナメントの参加表明をHTTPではなくWSで通信してユーザー目線で自動的に画面遷移してね、って設計記述に変えました。
技術詳細は実装の時に考えていただければと思います！

**Comment by tkuramot** [comment]
@jizots miroにコメントしました
