### ISSUE TITLE
『ポンゲームと対話するための必要なリソースとエンドポイントを公開するAPIを作成し、コマンドラインインターフェース（CLI）およびウェブインターフェースを介して部分的にゲームを使用できるようにする。』ってなに？

### ISSUE THREAD

**Issue by soma0822** [kaaaaakun/ft_transcendence#102]

**Comment by tkuramot** [comment]
前回の集まりで話した内容のまとめ
- `ポンゲームと対話するための必要なリソースとエンドポイントを公開するAPIを作成し`
  - サーバーサイドでPongゲームの処理をするためのWeb APIを作るという解釈。
- `コマンドラインインターフェース（CLI）およびウェブインターフェースを介して部分的にゲームを使用できるようにする`
  - `curl`などでWeb APIが叩ければ問題ない。部分的にともあるし、CLIのモジュールと違って完全に遊べるようにする必要はない

**Comment by tkuramot** [comment]
@soma0822 @soma0822 @jizots @kaaaaakun 

確認お願いします

**Comment by jizots** [comment]
記述していただいたことには異論ないです！　@tkuramot 

ただ、もう少し具体的に理解したいことは、例えば〜という内容です。（前回の集まりに出てないので聞き逃したのかもですけど）
サーバーサイドPongになると、サーバーサイドの計算をフロントに表示することがほとんどになる気がしていて、
curlのようなリクエスト、レスポンスでのAPIってPongゲーム画面であるんだろうか？と思っています。

どんな行為をCLIで行ったときに、どんなリアクションが返ってくるものが、この要求（部分的にゲームが利用できている）に対して達成したと解釈できそうなのでしょう？

**Comment by tkuramot** [comment]
> どんな行為をCLIで行ったときに、どんなリアクションが返ってくるものが、この要求（部分的にゲームが利用できている）に対して達成したと解釈できそう

マッチを作るREST APIについてもPongゲームの一部と捉えられるのでそれが一例になると思います
あとはwebsocketもcurlに対応するようなCLIツールがあるようなのでそれを使うことを考えればwebsocket APIを提供する時点で達成できそうです
