### ISSUE TITLE
オリジナルPongのゲーム動作の確認（ボール射出、反射、スピードなど）

### ISSUE THREAD

**Issue by soma0822** [kaaaaakun/ft_transcendence#104]

**Comment by soma0822** [comment]
スタート時は半分のスピードで、1度目の反射で普通のスピードになる
発射は自動でされる
反射は以下の計算式
`function V(a, c, d) {
    c = Math.PI / 4;  // 角度を設定
    d = d && O ? E / 2 : E;  // ボールの速度を設定
    a.i = (a.g ? 1 : -1) Math.cos(c) * d;  // X方向の速度
    a.c = Math.sin(c) * d;  // Y方向の速度
}`
π~- πとして、その角度に対してsin,cosをとっている

**Comment by soma0822** [comment]
@tkuramot @soragogo @jizots @kaaaaakun 
お願いします

**Comment by jizots** [comment]
パドルのどの位置に当たるかで反射角が変わりそうな挙動にも見えてますが、それも上記の計算に含まれてるのですかね？それともパドルとの接触位置に依存するものではない？　@soma0822

**Comment by soma0822** [comment]
一応入ってます！
文章難しいのでmiroに追加しておきます
