### ISSUE TITLE
ブロックチェーンの画面イメージ・要件・仕様詰め

### ISSUE THREAD

**Issue by kaaaaakun** [kaaaaakun/ft_transcendence#114]
@tkuramot @soma0822 @soragogo 以下レビューお願いします！

### 背景：
- ブロックチェーンの情報を表示する画面のデザインが決まっていない
- なんの情報を保存するかが決まっていない
### 目標：
- 画面イメージの作成
- 保存する情報を決める
--- 
## 方針
- 用語の確認
tx: トランザクション(ブロックチェーンにおける処理の申請書みたいなもの)

### 保存する情報
- `日時：マッチID：winner：loser：10対3` 
(内容としてはmatchesとmatch_detailsを合わせたようなもの)

### フロント側の変更
- 画面は増やさない
- ユーザーマネジメント部分の勝敗記録のところに表示
(確認用のpythonのコードは余裕があったらやりたい )
- テストコインの枯渇の可能性も考えて、できれば記録するかどうかは選択式にしたい。
(選択式の場合、どちらかのユーザーが記録したいと思ったら記録できるようにする)

| ユーザーマネジメント周り | 対戦画面まわり(できればやりたい) |
| --- | --- |
| ![Image](https://github.com/user-attachments/assets/94456685-ee47-4f32-8f2b-6bc90570d32e) | ![Image](https://github.com/user-attachments/assets/74fb6c3e-7528-441c-83c1-ca8b63f49340) |
- [ ] ユーザーマネジメントの画面作成時にBCも含めて設計
- [ ] 対戦画面のボタン追加・APIの変更[want]

### バックエンド
- [ ] txの作成からDBの記録まで
※ txが成功しなかった場合、再度txを作成する必要がある。
(今回ここまでやるかは微妙だが、whileで成功するまで回せばいいかな)
- [ ] マッチIDにtxの状態・txの保存を行うカラムの追加

---
### やってみたこと
- 自分で作成したトランザクションを実行して、保存・取り出し・レシートから取得したTXのアドレスの取得
[作成したコントラクト](https://sepolia.etherscan.io/address/0xc0E6bD0c26F33F3D9cd9AcA62F9eAbC87d9c82Ae)

**Comment by kaaaaakun** [comment]
- txってどのタイミングで実行されたかとか確認するか
- txが成功されなかった時に、再度txを作成する必要がある.(今回ここまでやるかは微妙)
- ユーザーマネジメントの勝敗一覧の画面の一部にトランザクションのアドレスを表示して、試合結果がテストネットに保存されていることを確認する。

[作成したコントラクト](https://sepolia.etherscan.io/address/0xc0E6bD0c26F33F3D9cd9AcA62F9eAbC87d9c82Ae)

**Comment by soragogo** [comment]
質問：
* 無料コインはいくらでも貰えると振り返りの中でおっしゃっていたので、コインが枯渇するイメージが湧きませんでした。コインを補充するためのリードタイムで困るということでしょうか？
* パイソンコードは個人個人で異なるものになるということでしょうか？

**Comment by jizots** [comment]
> 無料コインはいくらでも貰えると振り返りの中でおっしゃっていたので、コインが枯渇するイメージが湧きませんでした。コインを補充するためのリードタイムで困るということでしょうか？

そうです、リードタイムが必要です。
1日に無料でもらえるコイン量が決まっている（マニュアル操作でやるしかないからめんどくさい）
消費するコインの量が、ブロックチェーンの混み具合によって増えることがある（節約できたらしたい）

> パイソンコードは個人個人で異なるものになるということでしょうか？

はい、そうです。
もっと具体的には、対戦ごとに異なる（ただしトランザクションNoのみ異なる）というイメージです。 @soragogo
