### ISSUE TITLE
ELKを含めたコンテナ全体の図化

### ISSUE THREAD

**Issue by soma0822** [kaaaaakun/ft_transcendence#117]
**チケットの背景**
* DevOps設計のための設計の整理
* 要件の整理のためと、モジュールで取り組む内容をチーム内で共有することを目的とします。

**やりたいこと**
* ELKを含めたdockerアーキテクチャの全体像を図化する

**やらないこと**
* 実装はしない
* セキュリティ要件に関わる設計は省略（別チケット）
* ボリューム設計は省略（ymlファイルなど、設定ファイルが多めなので大事ではないと考えた）

**チケットの達成条件・確認項目**
 Miroボードの図と表を確認してレビューをお願いします。
[🔗link](https://miro.com/app/board/uXjVKDAW9_g=/?moveToWidget=3458764606486062694&cot=14)
 以下がわかれば、一旦ELKで何をするかわかる状態になっていると思うので、チケットの要件は達成できていることとします
* 各コンテナのログ情報を収集してくるコンテナはどれか。
* データが最終的に保存されるのはどこか。
* Kibanaで何ができるか。

その他気づいたことや不明点、不足している部分等があれば質問ください。

**Comment by kaaaaakun** [comment]
memo:
- １週間くらい調査する
- 別ツールで行けそうならそれで行く

- 上も微妙そうなら、もってぃに確認して
1. VM上にデプロイする（slackで見つけた対処案）
2. 全部のコンテナからログを収集することはできなくなるが、ログのアウトプット先を設定できるものだけログ収集する
3.自前PCでやるか
どれかを選ぶ

**Comment by soragogo** [comment]
update:
https://matsuand.github.io/docs.docker.jp.onthefly/config/containers/logging/configure/

logドライバの設定で、直接logstashコンテナにアウトプットする設定ができるみたいです。
なので、昨日話してた懸念事項はクリアできました。

設計図は後で更新しておきます。

**Comment by soragogo** [comment]
https://miro.com/app/board/uXjVKDAW9_g=/?moveToWidget=3458764606486062694&cot=14
@jizots @soma0822 
↑再レビューお願いします🙇‍♀️

ログドライバーの設定でlogstashにログを送り込めることがわかったので、この方針で行くと思います。

参考に、[dockerのドキュメント](https://matsuand.github.io/docs.docker.jp.onthefly/config/containers/logging/configure/)です
