### ISSUE TITLE
DockerコンテナログからLogstashにログを送信する方法の選定

### ISSUE THREAD

**Issue by soma0822** [kaaaaakun/ft_transcendence#118]

**Comment by soragogo** [comment]
#### チケットの背景
- DevOpsのモジュールの達成条件は、dockerコンテナからログを収集し、モニタリング・活用できるようにすることです。
- そこで、各コンテナから出力されたログを収集する必要がありますが、その方法がわからなかったので調査が必要でした。

#### やりたいこと
- モジュールの要件である、ELKを活用したログの収集方法の調査
- 特に、dockerコンテナ上でログを収集する方法についての調査
- 公式ドキュメントからできるだけエビデンスを見つけるようにする

#### やらないこと
- 実装などはここではやらない。調査と技術選定のみを行う。

#### チケットの達成条件・確認項目

- [ ] DevOpsモジュールの、このタスクに関連する以下の項目を確認し、要件とそれていないか確認する。
- [ ] Logstashを設定して、さまざまなソースからログデータを収集、処理、および変換し、それをElasticsearchに送信する。

---


###### レビュワー: @kaaaaakun, @kaaaaakun

**Comment by soragogo** [comment]
#### 結論
LogstashのプラグインであるFilebeatを使用する。
全体の設計については[こちらの図](https://miro.com/app/board/uXjVKDAW9_g=/?moveToWidget=3458764606486062694&cot=14)も参考にしてください。

#### Filebeatについて
* Elasticが開発した軽量なデータ収集ツール
* 指定したソースからログイベントを収集して、ElasticsearchやLogstashに転送する

概略図
 ![Image](https://github.com/user-attachments/assets/9e45278e-8fc5-41cf-a7fe-b730bdcb0d0d)


#### 選択肢として存在した他のログ収集ツール
* Fluentd
* syslog
* logspout

#### Filebeatを選定した観点
* Filebeatは軽量で、中小規模のプロダクトに向く。逆にFluentdなどは、大規模プロジェクト（数千台のサーバー展開など）の環境で使用できるが、そこまでの規模は今回は求められないと考えた。

**Comment by kaaaaakun** [comment]
@soragogo 
全体的に良さそうです！

一点質問があります
- Filebeatって専用のdockerコンテナが立ち上がる感じですか？
概略図を見る感じ、それぞれのコンテナ内部にあるのかな？と疑問に思いました。

**Comment by soragogo** [comment]
@kaaaaakun 
Filebeat専用のコンテナを立ち上げる予定です。
ELK関連で、新たに、
* Elasticsearch
* Logstash
* Kibana
* Filebeat
* Metricbeat
の５つのコンテナが立ち上がることになります。

**Comment by kaaaaakun** [comment]
@soragogo 
ありがとうございます！
LGTM✨です！

**Comment by tkuramot** [comment]
@soragogo 
良さそうです

**Comment by soragogo** [comment]
- [ ]
