### ISSUE TITLE
ELKスタックコンポーネントへのアクセスとログデータの保護のためのセキュリティ対策の調査

### ISSUE THREAD

**Issue by soma0822** [kaaaaakun/ft_transcendence#119]

**Comment by jizots** [comment]
Goodはしましたが、目的やゴールがあった方がレビューはしやすいかな〜と思いました。
例えば、IPアドレスの制限も、ロールやパスワードに加えて要求されているので、”どんなリスクがあるから”という目的設定があってやってるのか読み取れなかった等がありました。

**Comment by soragogo** [comment]
FYI：IPアドレスの制限は、Kibanaダッシュボード（ここからグラフとかが見れるやつです）に、そもそもユーザーがアクセスできないよう、登録したIPアドレスのみにアクセス許可を設定するやつです。

**Comment by kaaaaakun** [comment]
@soragogo 
具体的なタスクが生えるなら、書いてくれるとありがたいです！
設計図的なものがあるなら、miroか何かにまとめておいた方がいいかもと思いました。
