### ISSUE TITLE
フロントエンドで一時的な通知をするためのトーストを追加する

### ISSUE THREAD

**Issue by kaaaaakun** [kaaaaakun/ft_transcendence#139]
#### チケットの背景
- 一時的に表示される。error/login成功など...

#### やりたいこと
- 

#### やらないこと
- 

#### チケットの達成条件・確認項目

- [ ] 

---

###### レビュワー: @soragogo, @jizots

**Comment by tkuramot** [comment]
#130 で追加するフローティングバナーで、infoの時に一定時間で消すようにしたら良さそう
