### ISSUE TITLE
ユーザー認証方法の調査（どのような認証方法があるかと、どの方法を取るべきかの策定）

### ISSUE THREAD

**Issue by soragogo** [kaaaaakun/ft_transcendence#143]
#### チケットの背景
- ユーザーが登録したときに、ユーザー認証を行うのか、行うならどのような方法を取るかの要件定義を行います。
- このチケットが関連するのは以下の要求事項です。
- 1. Users can subscribe to the website in a secure way.
- 2. Registered users can log in in a secure way.
- これを満たすことが、このチケットの目的です。

#### やりたいこと
- ユーザーの認証の必要性の検証
- ユーザー認証をする場合、要件定義をする。

#### やらないこと
- お金がかかるようなやり方は基本策定しないです。

#### チケットの達成条件・確認項目

- [ ] チケットの背景で示した２つの要求事項をクリアできる認証方法であれば、達成
- [ ] その他違和感なく要件定義に賛同できれば、レビュー、👍をお願いします。

---

###### レビュワー: @kaaaaakun, @tkuramot

**Comment by soragogo** [comment]
【要件定義】
- ユーザー登録時は、任意のユーザーID＋パスワード＋秘密の質問（選択式）＋秘密の質問への答えで登録する
- ユーザーIDは、サイト内でニックネームとなりうるような、アルファベットと数字の文字列（n文字以上）のようなものを想定
- 登録時には、ユーザーIDの重複を避けるバリデーションを行う
- パスワードは、大文字＋小文字＋数字＋記号を含む10文字以上とする。[これ参考にした](https://security-portal.nisc.go.jp/guidance/pdf/handbook/NISC_handbook_general_20240531.pdf)
- ログイン時は、登録したユーザーID＋パスワードによってログインする
- パスワードを忘れた場合は、ユーザーID＋秘密の質問への答えによってパスワードの再設定を行う
　- ユーザーIDを送る⇨秘密の質問が現れる⇨答える⇨パスワードの再設定画面⇨無事アカウント復活

登録のユーザー認証などは行わない。

【結論に至った理由】
- メールアドレスによる認証なども考えられたが、メールサーバーが必要になるような手段は極力避けたかった
- ルールの設定によって、ユーザーIDとパスワードの設定のみで、モジュールで要求されている事項（descriptionのi, ii）を達成できると考えた
- また、リモートの認証については別モジュールに分かれていたので、このモジュールではそこまで手の込んだ認証を求められていないと考えた

---------
認証については、以上のように考えています。
いかがでしょうか。

**Comment by soragogo** [comment]
@kaaaaakun @tkuramot 
確認お願いします🙇‍♀️

**Comment by kaaaaakun** [comment]
@soragogo 
[ask]

> ユーザーIDは、サイト内でニックネームとなりうるような、アルファベットと数字の文字列（n文字以上）のようなものを想定

これって、ユーザー名はアルファベットの半角大文字小文字と数字どれを自由に使っても使わなくても良いという認識であってますか？
正規表現だとこれかな？ [\u\l\d] https://www.megasoft.co.jp/mifes/seiki/meta.html

**Comment by tkuramot** [comment]
[ask]
1. ハッシュ化するのはパスワードと秘密の質問への答えの二つでいいですか？

2. 秘密の質問を選択式にしていいのかが少し疑問でした。
パスワードを忘れた時に使うものになるので基本的に思い出しやすいものが設定されるはずで、
質問が決まっているなら答えも推測しやすく、突破されやすそうだなと思いました
質問自体もユーザーに決めさせる方法はあるのかなと思いました

[imo]
> ユーザーIDは、サイト内でニックネームとなりうるような、アルファベットと数字の文字列（n文字以上）

ユーザIDにはアンダースコアが許容されているアプリケーションは体感多いような気がしてます。
複数の単語を組み合わせてIDを作ろうとした時に区切り文字がなくなってしまうのでアンダースコアも許容した方がいいかもと思いました

メールによる認証を使わないと、仮にパスワードか秘密の質問が突破されてそれらが書き換えられた時にアカウント復旧の手立てがなくなってしまうなと思いました。そこまで求められているのかは判断によると思うので現状でも良いかもとは思います

**Comment by soragogo** [comment]
> [ask]
> 
> 1. ハッシュ化するのはパスワードと秘密の質問への答えの二つでいいですか？
> 2. 秘密の質問を選択式にしていいのかが少し疑問でした。
>    パスワードを忘れた時に使うものになるので基本的に思い出しやすいものが設定されるはずで、
>    質問が決まっているなら答えも推測しやすく、突破されやすそうだなと思いました
>    質問自体もユーザーに決めさせる方法はあるのかなと思いました
> 
> [imo]
> 
> > ユーザーIDは、サイト内でニックネームとなりうるような、アルファベットと数字の文字列（n文字以上）
> 
> ユーザIDにはアンダースコアが許容されているアプリケーションは体感多いような気がしてます。 複数の単語を組み合わせてIDを作ろうとした時に区切り文字がなくなってしまうのでアンダースコアも許容した方がいいかもと思いました
> 
> メールによる認証を使わないと、仮にパスワードか秘密の質問が突破されてそれらが書き換えられた時にアカウント復旧の手立てがなくなってしまうなと思いました。そこまで求められているのかは判断によると思うので現状でも良いかもとは思います


* ハッシュ化するのは、パスワードと秘密の質問への答えの二つの予定です。
* 秘密の質問についてですが、後述します。
* アンダースコアは入れてもいいかもしれませんね。


秘密の質問について、「質問自体をユーザーに決めさせる方法」についての逆質問です。
質問自体をユーザーに決めさせれば、答えが推測しにくいというのがあまりピンときませんでした。
私は、パスワード復旧時に質問内容は表示するような仕様を想定していました。
その場合は、質問がなんでも結局推測の容易さは変わらないような感じがします。
そうではなく、質問自体も覚えていないといけないような仕様にする場合、今度はユーザーの利便性が損なわれてしまうと思います。

**Comment by tkuramot** [comment]
> 秘密の質問について、「質問自体をユーザーに決めさせる方法」についての逆質問です。
質問自体をユーザーに決めさせれば、答えが推測しにくいというのがあまりピンときませんでした。
私は、パスワード復旧時に質問内容は表示するような仕様を想定していました。
その場合は、質問がなんでも結局推測の容易さは変わらないような感じがします。
そうではなく、質問自体も覚えていないといけないような仕様にする場合、今度はユーザーの利便性が損なわれてしまうと思います。

個別のアカウントをターゲットにして秘密の質問から答えを推測しようとするならその通りだと思います
任意のアカウントに対してという状況を考えた時に、質問が固定なのであればそれの答えになりうるリストを作るだけでどのアカウントに対しても広くアプローチが可能になってしまいそうだなと思いました

気にしなくてもいいかもしれないです

cf. https://www.expressvpn.com/jp/blog/how-to-choose-a-security-question/

**Comment by soragogo** [comment]
> > 秘密の質問について、「質問自体をユーザーに決めさせる方法」についての逆質問です。
> > 質問自体をユーザーに決めさせれば、答えが推測しにくいというのがあまりピンときませんでした。
> > 私は、パスワード復旧時に質問内容は表示するような仕様を想定していました。
> > その場合は、質問がなんでも結局推測の容易さは変わらないような感じがします。
> > そうではなく、質問自体も覚えていないといけないような仕様にする場合、今度はユーザーの利便性が損なわれてしまうと思います。
> 
> 個別のアカウントをターゲットにして秘密の質問から答えを推測しようとするならその通りだと思います 任意のアカウントに対してという状況を考えた時に、質問が固定なのであればそれの答えになりうるリストを作るだけでどのアカウントに対しても広くアプローチが可能になってしまいそうだなと思いました
> edit: 仕様に関しては自分も質問が表示されるのを想定してます

質問が固定だとブルートフォース的なことがしやすくなるってことですね。確かにこれは同意です。

**Comment by soragogo** [comment]
@tkuramot @kaaaaakun 
レビューの意見を反映し、要件定義に以下の追加をしました。

 * ユーザーIDに、アンダースコアも許可
 * 「秘密の質問」の質問内容は、選択式ではなく、ユーザーが作成した任意の質問

再レビューお願いします。

**Comment by tkuramot** [comment]
👍
