### ISSUE TITLE
画面設計

### ISSUE THREAD

**Issue by soragogo** [kaaaaakun/ft_transcendence#147]
#### チケットの背景
- #112 参照

#### やりたいこと
ユーザー登録、ユーザーログイン画面設計
ユーザープロフィール画面、編集画面、アバター画像
マッチ履歴の表示
フレンド申請（or　フォロー機能）

#### やらないこと
- 

#### チケットの達成条件・確認項目

- [ ] やりたいことを実現するために不足がないか

---

###### レビュワー: @jizots, @soma0822

**Comment by tkuramot** [comment]
https://miro.com/app/board/uXjVKDAW9_g=/?moveToWidget=3458764610558895429&cot=14
miroに追記しました
