### ISSUE TITLE
AsyncAPIの修正

### ISSUE THREAD

**Issue by kaaaaakun** [kaaaaakun/ft_transcendence#151]
#### チケットの背景
- トーナメント、2人対戦のエンドポイントが分割されていない（エンドポイントが1つしかない）

#### やりたいこと
- APIの修正
  - エンドポイントを1つふやす(中身はapi/ws/matchesと同じ)
   
#### やらないこと
- 特になし

#### チケットの達成条件・確認項目

- [ ]  エンドポイントが1つ増え、ペイロードはそれぞれ同じであること

---

###### レビュワー: @tkuramot, @soragogo   GPT choice

**Comment by jizots** [comment]
- ボール発射ボタンは存在しない設計です。ゲーム画面に切り替えたらボール位置が逐次送信されます。https://miro.com/app/board/uXjVKDAW9_g=/?moveToWidget=3458764604421547118&cot=14
- gameStopは画面イメージの何かよくわからない。。
- error系はsinagakiくんタスクでフォームとか決めてもらうのが先かもです
- トーナメントモードと２人対戦でエンドポイントが変わる必要があります（ビジネスロジックに記載されてたのを反映忘れ。バックロジックとしても必要）

**Comment by kaaaaakun** [comment]
@jizots
> ボール発射ボタンは存在しない設計です。ゲーム画面に切り替えたらボール位置が逐次送信されます。https://miro.com/app/board/uXjVKDAW9_g=/?moveToWidget=3458764604421547118&cot=14

なるほど、miroに情報あったの忘れてました。
ただ、これって画面遷移すると、勝手にボールが動き出すイメージですよね、
フロントの画面レンダリング中にバックエンドのボールの処理だけ進んで、得点が入ってそうだなと思いました。
↑の件、どう思います？ @soma0822 

> gameStopは画面イメージの何かよくわからない。。

miro確認忘れが原因なので、無視していただいてOKです。

> - error系はsinagakiくんタスクでフォームとか決めてもらうのが先かもです
> - トーナメントモードと２人対戦でエンドポイントが変わる必要があります（ビジネスロジックに記載されてたのを反映忘れ。バックロジックとしても必要）

あまりイメージついてないので、夜詰めたいです。
