### ISSUE TITLE
OpenAPI.yamlの更新（Simple対戦用の追加）

### ISSUE THREAD

**Issue by jizots** [kaaaaakun/ft_transcendence#153]
#### チケットの背景
- シンプル対戦のときにGame画面にプレイヤー名（固定L/R）をリターンするためのエンドポイントがない

#### やりたいこと
- OpenAPI.yamlの更新（シンプル対戦でゲーム画面の情報（プレイヤー名）をリクエストするエンドポイントを追加）
- エンドポイントuriの整理

#### やらないこと
- バックエンドの実装（既存のタスクでまきとる）

#### チケットの達成条件・確認項目

- [ ] シンプル対戦・トーナメント対戦用のエンドポイントが分離されている
- [ ] 追加されたエンドポイントの要求要素は基本同じ（トーナメントのみcookieを要求）

---
###### レビュワー: @soragogo, @tkuramot

**Comment by soragogo** [comment]
@jizots 
今日聞きそびれてしまったのですが、「シンプル対戦」とは何を指しますか？
コードを読んだ限り、local対戦の話かなと思いましたが、あっていますか？
