### ISSUE TITLE
フロントで描画に必要なデータの洗い出し

### ISSUE THREAD

**Issue by soma0822** [kaaaaakun/ft_transcendence#76]
サーバーからのメッセージで一意の描画に決まるように

**Comment by soma0822** [comment]
受け取るもの
プレイヤー：名前、得点
ゲーム：ボール、パドルの位置

送るもの
パドル移動の入力

ボールとパドルの位置の計算は全部API側が良さそう
（ただ足すだけならリソースをほとんど使わない。フロントで計算すると、一度ずれたものはずっと修正できなくなるため。）

**Comment by soragogo** [comment]
ボールの発射をユーザー側でやるのって、やめるんだっけ。それならこれでも良さそう。

**Comment by soma0822** [comment]
ああ、必要だわ

**Comment by soma0822** [comment]
> ボールの発射をユーザー側でやるのって、やめるんだっけ。それならこれでも良さそう。

**Comment by soma0822** [comment]
@tkuramot @soragogo @jizots 
レビューお願いします

**Comment by jizots** [comment]
1. ボール発射
どう実装するか考える必要がある部分だと思いました。
リモートプレイヤー対戦の場合、どちらかにボール発射の権限を与えるのか、どちらか先にボタン押した方を優先するのか、自動かなど。
これによって、フロントがサーバーに伝える情報なのかなど変わってきそうですね。
これは画面設計のフェーズで考えてもいいかもしれないですが、考慮すべき事項かなと。

2. 受け取るパドル位置
これは相手のパドル位置？もしくは自分のパドル位置も含める？かは今明確になるなら、してもいいかなと思いました。

画面設計の後で考える項目だったかもですね〜。　@soma0822

**Comment by soma0822** [comment]
1, ボール発射は確かに、設計して検討した方がいいですね。

2, 受け取るパドル位置は自分のも含めてを考えていました。pong
