### ISSUE TITLE
User managementのタスク分け　ブレスト

### ISSUE THREAD

**Issue by soma0822** [kaaaaakun/ft_transcendence#77]

**Comment by soma0822** [comment]
1. 調査、検討
・ユーザー名、メールアドレスの重複を許すか否か
・パスワードを安全に管理する方法
・メールアドレス認証の方法
・フレンド機能の仕様（フォローフォロワー形式、申請許諾形式）
・オンラインステータスの管理方法
・マッチの履歴をプロフィール欄に載せるか、別ページに作るか（subjectにプロフィール欄に勝敗を載せるとは別に書いてあった） 


2.設計
・データベース
・ユーザー登録、ユーザーログイン画面
・ユーザープロフィール画面、編集画面
・apiエンドポイント
・調査結果から必要なもの（フレンド機能等がまだわからない）
・フロントと

3.コーディング

**Comment by soma0822** [comment]
@tkuramot @soragogo @jizots @kaaaaakun 
レビューお願いします

**Comment by jizots** [comment]
①開発フェーズは置いといて、以下はタスク（orメモ)としてあってもいいかなと思いました。
- 標準的なユーザー管理としてのBAN機能、アカウント削除機能
- アバターの拡張子、容量
②2つのコメントに分かれてますが、タスクはどちらですか？両方なら合体させては？
③テストのフェーズはありますか？

**Comment by soma0822** [comment]
@jizots 
①確かに、追加しておきます。
②一つ目はほぼ、サブジェクトです。2つ目がこのタスクのメインです。
③テストのフェーズもありますが、設計ができてからかなと思っています

**Comment by jizots** [comment]
User managementのタスク分け、なのであれば要素は全部入れといた方がいいと思います！
これで要素分けすると実装とテストはタスクに無くなっちゃいそう。
「実装、テスト（設計後にタスクを細分化）」くらいのタスクはあってもいいのでは〜 @soma0822

**Comment by soma0822** [comment]
@jizots 
自分の認識では、最初のチケットを切るためのタスク分けのブレストだと思っていたんですけど、少し違いますか？

設計とかができるとそのまま必要なチケットが追加で切られていく、流れだと思っていました。

**Comment by jizots** [comment]
@soma0822 
> 最初のチケット

アジャイル開発において”最初のチケット”がどんなものかわかってないので、私もわからないです。。

> 設計とかができるとそのまま必要なチケットが追加で切られていく、流れだと思っていました。

これもまた、アジャイルでは何が暗黙の了解なのかがわかってないので、皆さんから学びたいと思います！
＊設計, 開発, テスト, リリースはチケットがなくてもマネジメントできるのか、誰が追加のチケット管理するのかわからなかった
