### ISSUE TITLE
Infrastructure　ブレスト

### ISSUE THREAD

**Issue by soma0822** [kaaaaakun/ft_transcendence#79]
0. 前提
* 目的→開発者がより効率よくログの確認を行えるようにするため。
* 集めるログ→Dockerコンテナから吐かれるログ全て
ブレスト： #

1. 調査
- [ ] ELKスタックコンポーネントへのアクセスとログデータの保護のためのセキュリティ対策の調査
2. 設計
- [ ] ELKを含めたコンテナ全体の図化
- [ ]  DockerコンテナログからLogstashにログを送信する方法の選定

3. 実装
- [ ] Elasticsearchコンテナの実装（ログのインデックス化、検索、アクセス用）
- [ ] Logstashコンテナの実装（ログを収集してログデータをElasticsearchに送信する用）
- [ ] Kibanaコンテナの実装（データをダッシュボードに可視化するよう）
- [ ] ログデータの保存・アーカイブポリシーの作成

4. 参考
[【超初心者向け】ELKStack超入門](https://qiita.com/tarosa0001/items/269bfa9ab8b82c410e5f)
[Elastic StackとDocker Composeを使いはじめる：パート1](https://elastic.co/jp/blog/getting-started-with-the-elastic-stack-and-docker-compose)
[Elastic StackとDocker Composeを使いはじめる：パート2](https://www.elastic.co/jp/blog/getting-started-with-the-elastic-stack-and-docker-compose-part-2)
[Dockerのログ収集方法の調査](https://qiita.com/rururu_kenken/items/48cd995c2da9a213bca3)「」

**Comment by soragogo** [comment]
1. 調査
* ELKスタックコンポーネントへのアクセスとログデータの保護のためのセキュリティ対策の調査

2. 設計
 * Elasticsearchコンテナの設計（ログのインデックス化、検索、アクセス用）
* Logstashコンテナの設計（ログを収集してログデータをElasticsearchに送信する用）
* Kibanaコンテナの設計（データをダッシュボードに可視化するよう）
* ログデータの保存・アーカイブポリシーの作成

3. 参考
[【超初心者向け】ELKStack超入門](https://qiita.com/tarosa0001/items/269bfa9ab8b82c410e5f)
[Elastic StackとDocker Composeを使いはじめる：パート1](https://elastic.co/jp/blog/getting-started-with-the-elastic-stack-and-docker-compose)
[Elastic StackとDocker Composeを使いはじめる：パート2](https://www.elastic.co/jp/blog/getting-started-with-the-elastic-stack-and-docker-compose-part-2)
[Dockerのログ収集方法の調査](https://qiita.com/rururu_kenken/items/48cd995c2da9a213bca3)

**Comment by soragogo** [comment]
@soma0822 @kaaaaakun @tkuramot @jizots 
Devopsについてまとめました。レビューお願いします🙇‍♀️
`3.参考`の一番上の記事はそもそもこのモジュールが何をするのかの理解にとても役立つと思うので前提把握したい方はぜひ読んでください！

**Comment by soragogo** [comment]
@jizots できれば再レビューお願いしたいです🙇

**Comment by jizots** [comment]
@soragogo ありがとうございます！
前提は後々、みんなで具体的に”空想”してもいいかなと思いました〜。
その方がKibanaやLog取得も設計しやすそう、という実装立場からの意見です

- ユーザー拡大のために、多言語対応のためにユーザーの多い国が知りたい！
- デプロイ後の、メンテナンス時間の設定のために利用時間帯が知りたい！
- デプロイ後の、サービス不具合を理解するためにHTTPステータスコードごとの統計が知りたい！
みたいな。現時点では👍です

**Comment by soragogo** [comment]
懸念点：
デプロイ時に検証用環境（無料）のまま提出していいのか
