### ISSUE TITLE
Block chainのタスク分け　ブレスト

### ISSUE THREAD

**Issue by soma0822** [kaaaaakun/ft_transcendence#80]
### 課題要件
- トーナメントスコアを直接ブロックチェーンに保存
- ブロックチェーンはEthereum
- 実装はテストチェーンに行う
- 開発言語はSolidity
- Solidityによるスマートコントラクトでスコアの記録・管理・取得が可能

### 独自要件
- 保存は1試合ごと
- feeを払うのは運営

### 調査・要件詰め
- [ ] Solidityを用いたデータの適切な保存の方法 
(配列などで保存していけるのか...など)
- [ ] マッチのデータそのものをどのような形に整形して保存するか
(DBのマッチを設計ごとそのまま保存でいいのか)
- [ ] バックエンドからスマートコントラクトを呼び出す仕組みの調査
- [ ] 「Solidityによるスマートコントラクトでスコアの取得」の画面イメージ・要件詰め

### 実装
- [ ] テスト用コインの取得
- [ ] Solidityによる実装
- データ保存部分
- データ取得部分
- [ ] バックエンド <-> スマートコントラクトの実装
- [ ] フロントの実装

### 用語解説

- solidty
イーサリアム用の開発言語
ブロックチェーン上にupする言語

### 参考
- [solidty](https://docs.soliditylang.org/en/v0.8.28/#solidity)
- [テスト用のブロックチェーン](https://qiita.com/tatsuya1970/items/ab28b2acad1ed9ef24ad)

### 10/14日に相談して決めたこと
- トーナメントスコア問題はマッチの結果を保存するのでよさそう
- 一旦保存するだけで、その値を使用する。という方向にはしなくていいのでは？
- タイミング：一点ごと、一試合ごとどっちでもよさそう。
- feeを払うのは運営でいいと思うとい話に

**Comment by kaaaaakun** [comment]
@soma0822 @tkuramot @soragogo @jizots 
Block chainのタスク分け/ブレストを行いました。
レビューお願いしますζ*'ヮ')ζ

**Comment by jizots** [comment]
ブレストありがとうございます！
サブジェクトの要素（要求）としてたりてないかも、と思ったことが2つかありました。

1. Store the score
->スコアを直接保存する方が要求を満たすことになるのでは。ハッシュから復号（元のスコアデータを再現）できるのかな。
2. contracts will be responsible for retrieving tournaments scores
->（おそらくブロックチェーンからの）トーナメントスコアのリトリーブの設計を忘れないようにしたいですね。

設計でたりてないかも
1. ブックチェーン関連の画面遷移（設計思想）
->どんな画面遷移でコントラクトがトランザクションを投げるのか。１試合ごとにユーザーがトランザクションを投げるか選択（自分でFeeを支払う）する、n試合ごとにコントラクト（運営がFeeを払って）が自動的にトランザクションを投げる、ゲーム参加時点でFeeを利用者が払う、など。

実装の方法は設計、調査段階で考えればいいと思いますよ〜。
タスクとしては大事そうな要素や、ちょっとしたTipsぐらいの方がブロックチェーン初心者でもレビューしやすいかも、です。

**Comment by kaaaaakun** [comment]
@jizots 
ありがとうございます！
そのままのスコアを保存するのはないと思って、頭から完全に抜けてました〜
ちょっと、今日明日動けないので、日曜の夜の段階で要件とかもう一度詰められたらと思います。

**Comment by kaaaaakun** [comment]
### 今気になってること・変更すべきところ

1. トーナメントスコアの記録・管理・取得とは？
> ◦ Solidity Smart Contracts: To interact with the blockchain, we will develop Solidity smart contracts. These contracts will be responsible for recording, managing, and retrieving tournament scores.

トーナメントスコアとは何を指しているか分からない。要相談
フロントでトーナメンを再現できるjsonデータがあればいいってこと？？

2.  Feeの話> ブックチェーン関連の画面遷移（設計思想）
->どんな画面遷移でコントラクトがトランザクションを投げるのか。１試合ごとにユーザーがトランザクションを投げるか選択（自分でFeeを支払う）する、n試合ごとにコントラクト（運営がFeeを払って）が自動的にトランザクションを投げる、ゲーム参加時点でFeeを利用者が払う、など。

要件がわからないので、自由に決めていい部分だと思う。
問題：タイミング・誰がfeeを払うか。
タイミング：一点ごと、一試合ごと、一トーナメントごと、任意の試合数ごと、など
誰が払うか：参加者・登録したい人・運営

3.リトリーブの設計
solidityを使うとあまり気にせずできるみたい。

4. マークルツリーに関して
使う必要ない予感

**Comment by kaaaaakun** [comment]
10月14日話し合いでの追記

- トーナメントスコア問題はマッチの結果を保存するのでよさそう
- 一旦保存するだけで、その値を使用する。という方向にはしなくていいのでは？
- タイミング：一点ごと、一試合ごとどっちでもよさそう。
- feeを払うのは運営でいいと思うとい話に

**Comment by kaaaaakun** [comment]
@soma0822 @jizots @kaaaaakun @tkuramot @soragogo 
Block chainのタスク分けに関して、だいたいイメージ決まったので、レビューお願いします。
Solidityを使ったblock chainへのデータの保存方式・方法に関しては別途調査したいと思っています。
https://github.com/kaaaaakun/ft_transcendence/issues/80#issue-2568560300
