### ISSUE TITLE
Server side pongのタスク分け　ブレスト

### ISSUE THREAD

**Issue by soma0822** [kaaaaakun/ft_transcendence#81]
1. 調査
- WebSocketのAPI通信の仕様書を調査してまとめる
- 『ポンゲームと対話するための必要なリソースとエンドポイントを公開するAPIを作成し、コマンドラインインターフェース（CLI）およびウェブインターフェースを介して部分的にゲームを使用できるようにする。』ってなに？
- 認証情報がWS通信でどのように利用されるか（ユーザー管理モジュールの導入時にOpenAPI的なのに影響があるなら考慮して設計するべきか）
- オリジナルPongのゲーム動作の確認（ボール射出、反射、スピードなど）
- 2人トーナメントの廃止and/orトーナメントではない対戦画面の実装の決定

2. 設計
- ユーザーが見る画面の構成、遷移、イメージ、機能
- エラー処理（通信の切断、バックからのエラーメッセージなど）の整理
- セキュリティリスクの整理
- パフォーマンスはどうあるべきか
- フロントの処理とバックの処理の切り分け
- WebsocketとHTTP通信の切り分け
- OpenAPI .yaml的なフロントが利用できるAPI仕様書の作成
- データベースの構成（頻繁な計算はDBではなくメモリを使うほうがいいのかも）
- APIビジネスロジック概要（エンドポイントとDBテーブルの関係性）
- APIの技術選定（ASGIサーバー選定、Websocketルーム）
- インフラ（コンテナ構成、サブジェクト記述のLinux対応）

3. コーディング
- フロント（バックからの情報を表示、パドル位置を送信、その他の設計機能）
- バック（パドル位置の受け取り、ボール位置の計算、パドルor壁orゴールとの接触判定、CLI）
- インフラ（リバースプロキシconf、Dockerfile、docker-compose、envなど）

4. テスト
- 画面構成
- API
- ユーザビリティ
- パフォーマンス
- セキュリティ

**Comment by jizots** [comment]
1. 調査
- 『ポンゲームと対話するための必要なリソースとエンドポイントを公開するAPIを作成し、コマンドラインインターフェース（CLI）およびウェブインターフェースを介して部分的にゲームを使用できるようにする。』ってなに？
- 認証情報がWS通信でどのように利用されるか（OpenAPI的なのに影響があるなら考慮して設計するべきか）
- オリジナルPongのゲーム動作の確認（ボール射出、反射、スピードなど）

2. 設計
- ユーザーが見る画面の構成、遷移、イメージ、機能
- エラー処理の整理
- セキュリティリスクの整理
- フロントの処理とバックの処理の切り分け
- OpenAPI .yaml的なフロントが利用できるAPI仕様書の作成
- データベースの構成
- インフラ（ASGIサーバー選定）

3. コーディング
- フロント（バックからの情報を表示、パドル位置を送信、その他の設計機能）
- バック（パドル位置の受け取り、ボール位置の計算、パドルor壁orゴールとの接触判定）
- インフラ（リバースプロキシ）

4. テスト
- 画面構成
- API
- ユーザビリティ
- セキュリティ

**Comment by jizots** [comment]
タスク分けのレビューをお願いします。
V字モデルの要領で、要素を洗い出してみました。
良さそうであれば上記コメントに👍を、追加などあればコメントにて教えてください。
質問系はDiscordがいいかなと思いました。よろしくお願いします！
@soma0822  @tkuramot  @soragogo  @kaaaaakun
