### ISSUE TITLE
ユーザーが見る画面の構成、遷移、イメージ、機能

### ISSUE THREAD

**Issue by soragogo** [kaaaaakun/ft_transcendence#83]
[miro](https://miro.com/app/board/uXjVKDAW9_g=/?moveToWidget=3458764604421547117&cot=14)にて”画面遷移”と”画面イメージ”を確認してください。
あくまでユーザー視点であり、エンジニアリングに関わる部分は極力含めていません。

**Comment by jizots** [comment]
@soma0822 @soragogo @kaaaaakun @tkuramot 
レビューお願いします

**Comment by soma0822** [comment]
@jizots 
ありがとうございます！

1. ボタン押した時のPOST・GETリクエストがAPIに対してのものとフロント完結のものがまざってまざっているのがわかりにくいかもしれないです。

2.miroから飛べるpongゲームは10点でゲームが終わりました。
![Image](https://github.com/user-attachments/assets/2941d7a9-f09b-4ffa-81e2-4a5d3bc88916)

**Comment by jizots** [comment]
@soma0822 　ありがとうございます。
> ボタン押した時のPOST・GETリクエストがAPIに対してのものとフロント完結のものがまざってまざっているのがわかりにくいかもしれないです。

”こうしたい”という要望もないようなので、GETなのかPOSTなのかも含めて記述するのをやめました。
あくまでユーザー視点がメインなので、エンジニアリングの部分は含めなくていいかなと思いました。
もしエンジニアリング部分での追加が必要であれば、何を期待するかを記述して別チケットがいいかなと思いました！

> 2.miroから飛べるpongゲームは10点でゲームが終わりました。

根拠の記述がありませんでした。失礼しました。
参照
[Atari Pong](https://atari.fandom.com/wiki/Atari_Pong)
<img width="811" alt="Screenshot 2024-10-27 at 18 51 45" src="https://github.com/user-attachments/assets/293e8912-a006-4679-a93a-2e16cb976a93">

**Comment by kaaaaakun** [comment]
@jizots 
ありがとうございます！

トーナメントとは別にある2人対戦についてはここには記述がなくても大丈夫な感じですか？

**Comment by jizots** [comment]
@kaaaaakun 記述はあります。ホーム画面からゲーム画面への遷移がいわゆる”2人対戦”です

**Comment by soma0822** [comment]
@jizots
2点追加の質問です！
1, 左記と書いてありますが、全部右記ですか？
2, 二人対戦の時のゲーム終了時、トーナメントの時のトーナメント終了時はホームに戻るのは左上のアイコンからのみですか？

**Comment by jizots** [comment]
@soma0822 
> 1, 左記と書いてありますが、全部右記ですか？ 

左側に記述のある動作をする、という意味で”左記”、としています。
なので記述に間違いはないつもりです。

>2, 二人対戦の時のゲーム終了時、トーナメントの時のトーナメント終了時はホームに戻るのは左上のアイコンからのみですか？

はい、最小限の動作要求はその通りです。
前提に記述があるように、実装での”追加”は自由です。
