### ISSUE TITLE
フロントの処理とバックの処理の切り分け

### ISSUE THREAD

**Issue by soragogo** [kaaaaakun/ft_transcendence#87]
ref: https://github.com/kaaaaakun/ft_transcendence/issues/76

why: ASyncAPIの記述、スムーズなコーディングのため
what: 画面に表示される情報について、フロントもしくはバックが相互作用、生成および保存を担うのかの明確化

トーナメント時
フロント：プレイヤー名の入力受付。プレイヤー名をAPIに送信
API：プレイヤー名をもとにトーナメントを作成。トーナメント情報を送信
フロント：トーナメントidをAPIに送信
API：トーナメントidをもとにmatchの生成。match情報の送信
フロント：keyeventの送信（パドル操作）
API：ボールの位置、パドルの位置、得点、match終了の判定の処理を行い、結果を送信
試合終了後
フロント：トーナメントidを送信
API：トーナメント情報を返す
フロント：トーナメントid を送信
API：トーナメントidをもとにmatchの生成。match情報の送信
以下ループ

二人対戦
フロント：二人対戦をリクエスト
API：プレイヤー名をL,Rとしてマッチを作成。マッチ情報を送信
以下トーナメント時と同じ

**Comment by jizots** [comment]
ブレストありがとうございます
1. ゲームのWall
ゲーム画面で表示されるWall（Pongの壁）ってたぶんAPIとフロントで同じものを持つ必要がありますよね。
ということはAPIが壁位置も送るか、もしくは同じものを持つように両方で設計を合わせるか。

2. オンライン
ラベル的に、リモートプレイヤーの視点はレビューしてません。
他のレビューとの統一性のためです。

3. ボール発射のカウントダウン（重要ではない）
面白そうですが、いきなり発射でもいいかなと思いました。

4.得点の判定
これもAPIの仕事？パドルとボールの接触も

**Comment by soma0822** [comment]
@jizots 
レビューありがとうございます。
1. ゲームのWall
検討していなかったです。画面の大きさ、ボールの大きさ、パドルの大きさ、ボールの位置などを相対的な大きさにして送ったほうがAPIとしての汎用性が大きくなりそうです。検討します。

4.得点の判定
順番前後します。
リモートプレイヤーを考えたらそれぞれのフロントで判定させるよりも効率が良いと考えます。

2.オンライン
4のようにリモートプレイヤーも多少考慮したため一応書きました。

**Comment by soma0822** [comment]
ゲームのWall（画面サイズ）について

APIを作るのは他アプリや、他開発者でもそのAPIを利用することで簡単にサービスを作ることができることだと思うので、そこを基準にして記述します。

結論：APIの仕様として、画面の大きさや、ボールの大きさ、パドルの大きさを固定値で決めてそれに合わせてフロントを作るのが良いと思う。

理由１：フロント側で自由に決めることができるメリットが少ない。（ボールの大きさを変更したり、パドルの大きさを変更したりすることは本来のpongから離れる行為であるため、できる必要がない）
理由２：相対的な大きさで送る必要がない（画面の大きさを100*100とかにして相対的な大きさで送ることと、画面の大きさを600*400で送ることは本質的には変わらない（フロント側でそれぞれを割り引くだけで良い））

**Comment by soma0822** [comment]
@soragogo @jizots @tkuramot @kaaaaakun 
コメントではなく、ディスクリプションに追記しました
