### ISSUE TITLE
WebsocketとHTTP通信の切り分け

### ISSUE THREAD

**Issue by soragogo** [kaaaaakun/ft_transcendence#88]
why: ASyncAPIの記述のため
what: 画面遷移もしくは画面動作のどのポイントでWebSocket通信を利用する（開始、接続中および終了）かの設計

レビューお願いします。
miroに図示しました。
https://miro.com/app/board/uXjVKDAW9_g=/?moveToWidget=3458764606020567286&cot=14
ユーザー目線では、以下のタイミング
開始：”Play Now”ボタンもしくは”Start Match”ボタンが押下で
終了：スコアが終了点に達した時にすぐに、サーバー側で

@tkuramot @soma0822 @soragogo @kaaaaakun

**Comment by kaaaaakun** [comment]
どこからが、HTTP通信かWebsocketを決める
