### ISSUE TITLE
データベースの構成（頻繁な計算はDBではなくメモリを使うほうがいいのかも）

### ISSUE THREAD

**Issue by soragogo** [kaaaaakun/ft_transcendence#90]
why: APIコーディングをスムーズに行うためのDB設計
what: バックエンドで保存する情報の整理、RDBMSを利用する情報のテーブル構成、一時メモリを利用する情報の管理方法の記述

e.g. [25%のDB設計](https://miro.com/app/board/uXjVKDAW9_g=/?moveToWidget=3458764596033550581&cot=14)

レビュー対象
https://miro.com/app/board/uXjVKDAW9_g=/?moveToWidget=3458764605516714740&cot=10

redisをwebsocket roomで使うんじゃないかという話について
結論：ひとまずこのままで良い
・websocket roomでredis は使うことになりそう
・リモートプレイヤーとローカルでのポンゲームでは残す情報に差異がありそう。
・サーバーサイドポン（リモートプレイヤー抜き）ではこのままで、リモートプレイヤーの時に検討するべきである

**Comment by soma0822** [comment]
redisの利用の検討

**Comment by kaaaaakun** [comment]
- 頻繁な計算はDBではなくメモリを使うほうがいいのかもの話

### redisを導入する場合
- メリット
APIサーバーが落ちて、接続が切れた時とかにユーザーが復活できない。
という場合のために、redishサーバーみたいなものが必要
ゲームで 使われているらしいから、問題なさそう
- デメリット
あまり落ちることはないのでは？
コンテナを別で建てる必要がある
通信が新たに

### 導入しない場合
- メリット
プレイヤーが切断しときに復帰できるかどうか
サーバー側でクライアントと通信が切れたら、保存するとかができそう。
コントローラーの方がはやい
- デメリット
落ちた時に復帰できない。

**Comment by soma0822** [comment]
@kaaaaakun @tkuramot  @jizots @soragogo 
ディスクリプションにmiroのlink置きました。
レビューお願いします。

下にredisの使い方のサンプルコード置いておきます。

`const express = require('express');
const http = require('http');
const Redis = require('ioredis');
const { Server } = require('socket.io');

const app = express();
const server = http.createServer(app);
const io = new Server(server);
const redis = new Redis(); // デフォルトでlocalhostの6379に接続

app.use(express.json());

io.on('connection', (socket) => {
  console.log('A user connected');

  // プレイヤーを初期登録するリクエストを受け取る
  socket.on('registerPlayer', async (data) => {
    const { tournamentId, matchId, player, initialScore = 0 } = data;
    if (!tournamentId || !matchId || !player) {
      socket.emit('error', 'Tournament ID, Match ID, and Player name are required');
      return;
    }

    try {
      // RedisのキーとしてトーナメントIDとマッチID、プレイヤー名を使い、初期スコアを設定
      const key1 = `score:${tournamentId}:${matchId}:${player}`;
      const key2 = `tournament:${tournamentId}:player:${player}`;
      await redis.set(key1, initialScore);
      await redis.set(key2, initialScore);
      socket.emit('playerRegistered', `Player: ${player} registered in tournament: ${tournamentId}, match: ${matchId} with initial score: ${initialScore}`);
    } catch (err) {
      console.error('Error registering player:', err);
      socket.emit('error', 'Internal Server Error');
    }
  });

  // スコアを加算するリクエストを受け取る
  socket.on('scoreUpdate', async (data) => {
    const { tournamentId, matchId, player } = data;
    if (!tournamentId || !matchId || !player) {
      socket.emit('error', 'Tournament ID, Match ID, and Player name are required');
      return;
    }

    try {
      // RedisのキーとしてトーナメントIDとマッチID、プレイヤー名を使い、スコアをインクリメント
      const key1 = `score:${tournamentId}:${matchId}:${player}`;
      const key2 = `tournament:${tournamentId}:player:${player}`;
      await redis.incr(key1);
      await redis.incr(key2);
      socket.emit('scoreUpdated', `Score updated for player: ${player} in tournament: ${tournamentId}, match: ${matchId}`);
    } catch (err) {
      console.error('Error updating score:', err);
      socket.emit('error', 'Internal Server Error');
    }
  });

  // プレイヤーの現在のスコアを取得するリクエストを受け取る
  socket.on('getScore', async (data) => {
    const { tournamentId, matchId, player } = data;

    if (!tournamentId || !matchId || !player) {
      socket.emit('error', 'Tournament ID, Match ID, and Player name are required');
      return;
    }

    try {
      // RedisからトーナメントID、マッチID、プレイヤーのスコアを取得
      const key = `score:${tournamentId}:${matchId}:${player}`;
      const score = await redis.get(key);
      socket.emit('scoreData', { tournamentId, matchId, player, score: score || 0 });
    } catch (err) {
      console.error('Error fetching score:', err);
      socket.emit('error', 'Internal Server Error');
    }
  });

  socket.on('disconnect', () => {
    console.log('A user disconnected');
  });
});

// サーバーを起動
const PORT = 3000;
server.listen(PORT, () => {
  console.log(`Server is running on http://localhost:${PORT}`);
});
`

**Comment by jizots** [comment]
miroにボール、パドルなどの情報の保持箇所についてコメントしました。

**Comment by kaaaaakun** [comment]
#94 と関連して、追加調査が必要

-元々の予定
redisをデータベースとして使う
- リモートプレイヤーのことを意識すると
djangoチャネルのwebsoket room を使ってクライアント同士の通信をするときに、
redisのメモリ上で実行した方が良さそうということがわかった。
ただ、動かしてみないとよく分からなさそう。

**Comment by kaaaaakun** [comment]
@soma0822 一点miroにメモしました！
