### ISSUE TITLE
APIビジネスロジック概要（エンドポイントとDBテーブルの関係性）

### ISSUE THREAD

**Issue by soragogo** [kaaaaakun/ft_transcendence#91]
why: ASyncAPIの記述およびAPIのコーディングをスムーズに行うための準備
what: どの画面で、どのようなトリガーによるAPIがあり、どんなIN \OUT情報で、バックエンドではDB（含むメモリ）をどのように更新するのかを設計する

e.g. [25%のAPIエンドポイントの概略図（とビジネスロジック）](https://miro.com/app/board/uXjVKDAW9_g=/?moveToWidget=3458764596510962673&cot=14)

**Comment by kaaaaakun** [comment]
memo:
リモートプレーヤーは一旦あとで考える
#90 と依存関係にある

**Comment by soragogo** [comment]
25%pongから追加した箇所は以下の通りです。
「ポンゲーム対戦画面」（この部分がおそらくHTTP通信でなくwebsocketになるだろうという前提で書いています）

クライアント側 : 
* ユーザーのキー操作を送る

サーバー側 :
* ユーザーのキー操作がある場合はユーザーのパドル位置を更新する
* 逐次処理としては、ボール位置の更新、スコアの更新を行う
* ゲーム終了点に到達した場合はMatchDetails、Match、TournamentPlayersなどの既存行を更新する

詳細は以下で確認をお願いします！🙇‍♀️
Refs: https://miro.com/app/board/uXjVKDAW9_g=/?moveToWidget=3458764604861437825&cot=14

**Comment by kaaaaakun** [comment]
@soragogo 
websoketだと`ユーザーのキー操作`と`逐次処理`が一緒になるかなという印象です.
ちょっとAsyncAPI書いてみないと分からないけど、、、

**Comment by soragogo** [comment]
@soma0822 @kaaaaakun @jizots @tkuramot 
修正したので再レビューお願いしたいです🙇‍♀️
https://miro.com/app/board/uXjVKDAW9_g=/?moveToWidget=3458764604861437825&cot=14
