### ISSUE TITLE
APIの技術選定（ASGIサーバー選定、Websocketルーム）

### ISSUE THREAD

**Issue by soragogo** [kaaaaakun/ft_transcendence#92]

**Comment by soma0822** [comment]
@soragogo @tkuramot @jizots @kaaaaakun 
項目 | WebSocketルーム | ASGIサーバー
-- | -- | --
目的 | クライアント間のリアルタイム通信の管理 | 非同期通信プロトコルのサポート (例: WebSocket, HTTP/2)
役割 | 特定のルーム内でのクライアント間通信を管理 | アプリケーションとプロトコル間の橋渡しをするインターフェース
適用範囲 | WebSocket通信の管理、ルーム単位のクライアント管理 | アプリ全体での非同期リクエストの処理
例 | チャットルーム、ゲームルーム | WebSocket、HTTP/2の処理、DaphneやUvicorn



`ASGIサーバーにはいくつか選択肢があります。以下は代表的なASGIサーバーと、それぞれの特徴です。

1. Uvicorn
特徴: 最も人気があり、軽量で高性能なASGIサーバー。
推奨用途: 高速な非同期Webアプリケーションに最適。特にFastAPIなどと組み合わせて使用されることが多い。
対応機能: WebSockets、HTTP/2、ASGI 3.0に完全対応。
メリット: 開発のしやすさ、シンプルな設定、パフォーマンスが良い。
2. Daphne
特徴: Djangoのチャンネルプロジェクトによって開発されたASGIサーバー。
推奨用途: Django Channelsを使用しているプロジェクトに最適。
対応機能: WebSocketsや長時間接続に適している。
メリット: Djangoプロジェクトでの使用を前提に設計されているため、Djangoユーザーにとって使いやすい。
3. Hypercorn
特徴: 高度なカスタマイズが可能なASGIサーバー。
推奨用途: 高度な設定やカスタマイズが必要な場合に有用。
対応機能: HTTP/2やQUIC、ASGI 3.0をサポート。
メリット: 様々なプロトコルをサポートし、柔軟な設定が可能。
4. Starlette
特徴: Uvicornとよく組み合わせられる軽量なASGIフレームワーク。
推奨用途: Uvicornと連携した軽量なアプリケーションに適している。
対応機能: WebSocket、SSE、HTTP/2。
メリット: Uvicornと一緒に使うことで非常に高速で効率的。
選定基準

パフォーマンス: 高パフォーマンスが必要ならUvicornが最も適しています。
フレームワークの互換性: Djangoを使っているならDaphneが良い選択です。
カスタマイズ: 高度な設定が必要な場合はHypercornが向いています。
軽量さ: 軽量でシンプルなサーバーを求めているならUvicornやStarletteが良いでしょう。
使用しているフレームワークやプロジェクトの規模、必要な機能に応じて選ぶと良いです。`
by ChatGPT


Djangoとの相性や使いやすさをみて
ASGIサーバー：Daphne
Websocketルーム：Django Channels
が良さそう

**Comment by soma0822** [comment]
websocket ルームはリモートプレイヤー考えなかったら、必要ない
