### ISSUE TITLE
websocketライブラリ決め

### ISSUE THREAD

**Issue by tkuramot** [kaaaaakun/ft_transcendence#93]
フロントエンドだったらweb標準のもあるけどそれ含めてどうするか etc.

**Comment by jizots** [comment]
◆フロント

◆バック

**Comment by jizots** [comment]
@tkuramot @soma0822 @soragogo @kaaaaakun 
レビューお願いします！
簡潔な結論は以下です。
フロントは、**Web標準のJavaScript WebSocket API**を利用
サーバーサイドは、Djangoを非同期対応するために**DjangoChannels**を利用
