### ISSUE TITLE
インフラ（コンテナ構成、サブジェクト記述のLinux対応）

### ISSUE THREAD

**Issue by soragogo** [kaaaaakun/ft_transcendence#94]
why: 開発をスムーズに行うためにインフラの設計を明確にしておく
what: コンテナの数、役割、ボリューム、メインプロセス、ネットワークに関連する図。加えて、サブジェクトの記述が何を意味するのかも説明を図に加える。
e.g. [25%のコンテナの概略図](https://miro.com/app/board/uXjVKDAW9_g=/?moveToWidget=3458764596603828050&cot=14)

レビュー対象
https://miro.com/app/board/uXjVKDAW9_g=/?moveToWidget=3458764605521240632&cot=14

**Comment by soma0822** [comment]
@jizots 
https://miro.com/app/board/uXjVKDAW9_g=/?moveToWidget=3458764605521240632&cot=14

gunicornをdaphneに置き換えて、redisを追加するだけで良いさそうなのですが、いかがですか？
何か話す必要あれば、4,5日の21時以降お願いします。

**Comment by soma0822** [comment]
@soragogo @tkuramot @kaaaaakun 
レビューお願いします

**Comment by soragogo** [comment]
レビュー遅くなりました🙇‍♀️問題ないと思います。
