### ISSUE TITLE
パドル、ボールのデータ送信をどれくらいの間隔で送るのか

### ISSUE THREAD

**Issue by tkuramot** [kaaaaakun/ft_transcendence#97]

**Comment by soragogo** [comment]
@tkuramot @soma0822 @jizots @kaaaaakun 
オリジナルのpong gameでは、描画のインターバルを`60フレーム/秒`で設定している
パフォーマンスを見て調整をする必要があるかもしれませんが、一旦はここを基準としてはどうでしょうか。

また、鎌田調べですが、人の目で見てスムーズに感じられるのは24-30fps程度なので
パフォーマンスを考慮したとしても、最低でも30フレーム/秒以上のパフォーマンスは必須だと考えています。

https://www.ponggame.org/compiled-2.js
https://t-r-a-m.jp/garage/staff-blog/what-is-frame-rate/
